import http from './httpClient'

const unwrap = (request) => request.then(({ data }) => data)

export const realApi = {
  login: (body) => unwrap(http.post('/auth/login', body)),
  me: () => unwrap(http.get('/auth/me')),
  logout: () => unwrap(http.post('/auth/logout')),
  updateProfile: (body) => unwrap(http.patch('/auth/profile', body)),
  changePassword: (body) => unwrap(http.patch('/auth/password', body)),
  getRoles: () => unwrap(http.get('/roles')),
  getUsers: (params) => unwrap(http.get('/users', { params })),
  getUser: (id) => unwrap(http.get(`/users/${id}`)),
  createUser: (body) => unwrap(http.post('/users', body)),
  updateUser: (id, body) => unwrap(http.patch(`/users/${id}`, body)),
  updateUserStatus: (id, status) => unwrap(http.patch(`/users/${id}/status`, { status })),
  getSubjects: () => unwrap(http.get('/subjects')),
  getSubject: (id) => unwrap(http.get(`/subjects/${id}`)),
  createSubject: (body) => unwrap(http.post('/subjects', body)),
  updateSubject: (id, body) => unwrap(http.patch(`/subjects/${id}`, body)),
  deleteSubject: (id) => unwrap(http.delete(`/subjects/${id}`)),
  getChapters: (params) => unwrap(http.get('/chapters', { params })),
  getChapter: (id) => unwrap(http.get(`/chapters/${id}`)),
  createChapter: (body) => unwrap(http.post('/chapters', body)),
  updateChapter: (id, body) => unwrap(http.patch(`/chapters/${id}`, body)),
  deleteChapter: (id) => unwrap(http.delete(`/chapters/${id}`)),
  getQuestions: (params) => unwrap(http.get('/questions', { params })),
  getQuestion: (id) => unwrap(http.get(`/questions/${id}`)),
  createQuestion: (body) => unwrap(http.post('/questions', body)),
  updateQuestion: (id, body) => unwrap(http.patch(`/questions/${id}`, body)),
  deleteQuestion: (id) => unwrap(http.delete(`/questions/${id}`)),
  getAvailability: (params) => unwrap(http.get('/questions/availability', { params })),
  getMatrices: (params) => unwrap(http.get('/exam-matrices', { params })),
  getMatrix: (id) => unwrap(http.get(`/exam-matrices/${id}`)),
  createMatrix: (body) => unwrap(http.post('/exam-matrices', body)),
  updateMatrix: (id, body) => unwrap(http.patch(`/exam-matrices/${id}`, body)),
  deleteMatrix: (id) => unwrap(http.delete(`/exam-matrices/${id}`)),
  generatePapers: (id, body) => unwrap(http.post(`/exam-matrices/${id}/generate`, body)),
  getPapers: (params) => unwrap(http.get('/exam-papers', { params })),
  getPaper: (id) => unwrap(http.get(`/exam-papers/${id}`)),
  deletePaper: (id) => unwrap(http.delete(`/exam-papers/${id}`)),
  getDashboard: () => unwrap(http.get('/dashboard/summary')),
}
