import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/service'
import { useAuth } from '../auth/AuthContext'
import { ConfirmModal, EmptyState, ErrorState, FieldError, LoadingState, Modal, PageHeader } from '../components/UI'
import { useToast } from '../components/ToastProvider'

function ChapterForm({ item, subjects, chapters, selectedSubject, onClose }) {
  const queryClient = useQueryClient(); const { notify } = useToast(); const { register, handleSubmit, setError, watch, formState: { errors } } = useForm({ defaultValues: item || { name: '', orderIndex: 1, subjectId: selectedSubject || '' } }); const subjectId = watch('subjectId')
  const mutation = useMutation({ mutationFn: (body) => item ? api.updateChapter(item.id, body) : api.createChapter(body), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['chapters'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); queryClient.invalidateQueries({ queryKey: ['availability'] }); notify(item ? 'Đã cập nhật chương' : 'Đã thêm chương'); onClose() }, onError: (error) => { Object.entries(error.fieldErrors || {}).forEach(([name, message]) => setError(name, { message })); if (!error.fieldErrors || !Object.keys(error.fieldErrors).length) setError('root', { message: error.message }) } })
  const submit = (values) => { const duplicate = chapters.some((c) => c.id !== item?.id && c.subjectId === Number(values.subjectId) && c.orderIndex === Number(values.orderIndex)); if (duplicate) return setError('orderIndex', { message: 'Số thứ tự đã tồn tại trong môn học' }); mutation.mutate({ ...values, subjectId: Number(values.subjectId), orderIndex: Number(values.orderIndex) }) }
  return <Modal title={item ? 'Sửa chương' : 'Thêm chương'} onClose={onClose}><form onSubmit={handleSubmit(submit)}>{errors.root && <div className="alert error">{errors.root.message}</div>}<label>Môn học<select {...register('subjectId', { required: 'Vui lòng chọn môn học' })}><option value="">Chọn môn học</option>{subjects.map((s) => <option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select></label><FieldError>{errors.subjectId?.message}</FieldError><label>Tên chương<input maxLength="50" {...register('name', { required: 'Tên chương là bắt buộc', maxLength: { value: 50, message: 'Tối đa 50 ký tự' } })} /></label><FieldError>{errors.name?.message}</FieldError><label>Số thứ tự<input type="number" min="1" {...register('orderIndex', { required: 'Số thứ tự là bắt buộc', min: { value: 1, message: 'Giá trị tối thiểu là 1' }, valueAsNumber: true })} /></label><FieldError>{errors.orderIndex?.message}</FieldError><p className="form-help">Số thứ tự phải duy nhất trong môn học {subjects.find((s) => s.id === Number(subjectId))?.name || 'đã chọn'}.</p><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Hủy</button><button className="button" disabled={mutation.isPending}>{mutation.isPending ? 'Đang lưu...' : 'Lưu chương'}</button></div></form></Modal>
}

export default function ChaptersPage() {
  const { user } = useAuth()
  const isAdmin = user?.role === 'ADMIN'
  const [params, setParams] = useSearchParams(); const selected = params.get('subjectId') || ''; const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const { notify } = useToast(); const queryClient = useQueryClient()
  const subjects = useQuery({ queryKey: ['subjects'], queryFn: api.getSubjects }); const chapters = useQuery({ queryKey: ['chapters', selected], queryFn: () => api.getChapters(selected ? { subjectId: selected } : {}) }); const allChapters = useQuery({ queryKey: ['chapters', 'all'], queryFn: () => api.getChapters({}) })
  const deleteMutation = useMutation({ mutationFn: api.deleteChapter, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['chapters'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); queryClient.invalidateQueries({ queryKey: ['availability'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); notify('Đã xóa chương'); setDeleting(null) }, onError: (error) => notify(error.message, 'error') })
  const loading = subjects.isLoading || chapters.isLoading
  return <><PageHeader title="Quản lý chương" description="Sắp xếp chương theo từng môn học." action={isAdmin && <button className="button" onClick={() => setEditing({})}>Thêm chương</button>} /><div className="toolbar"><label>Bộ lọc môn học<select value={selected} onChange={(e) => setParams(e.target.value ? { subjectId: e.target.value } : {})}><option value="">Tất cả môn học</option>{(subjects.data || []).map((s) => <option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select></label></div>
    {loading ? <LoadingState /> : chapters.isError || subjects.isError ? <ErrorState error={chapters.error || subjects.error} onRetry={() => { chapters.refetch(); subjects.refetch() }} /> : !chapters.data.length ? <EmptyState title="Chưa có chương" description="Hãy thêm chương đầu tiên cho môn học." /> : <div className="table-wrap"><table><thead><tr><th>STT</th><th>Tên chương</th><th>Môn học</th><th>Thao tác</th></tr></thead><tbody>{chapters.data.map((item) => { const subject = subjects.data.find((s) => s.id === item.subjectId); return <tr key={item.id}><td>{item.orderIndex}</td><td><strong>{item.name}</strong></td><td>{subject?.name || '—'}</td><td><div className="table-actions">{isAdmin && <><button className="text-button" onClick={() => setEditing(item)}>Sửa</button><button className="text-button danger-text" onClick={() => setDeleting(item)}>Xóa</button></>}</div></td></tr> })}</tbody></table></div>}
    {editing && <ChapterForm item={editing.id ? editing : null} subjects={subjects.data || []} chapters={allChapters.data || []} selectedSubject={selected} onClose={() => setEditing(null)} />}{deleting && <ConfirmModal message={`Xóa chương “${deleting.name}”?`} onClose={() => setDeleting(null)} onConfirm={() => deleteMutation.mutate(deleting.id)} busy={deleteMutation.isPending} />}
  </>
}
