import { useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { api } from '../api/service'
import { DIFFICULTIES, difficultyLabel } from '../constants'
import { formatDate } from '../utils'
import { Badge, ConfirmModal, EmptyState, ErrorState, FieldError, LoadingState, Modal, PageHeader, Pagination } from '../components/UI'
import { useToast } from '../components/ToastProvider'

const keyOf = (chapterId, difficulty) => `${chapterId}-${difficulty}`

function ConfigTable({ chapters, availability, quantities, setQuantity }) {
  return <div className="table-wrap matrix-config"><table><thead><tr><th>Chương</th>{DIFFICULTIES.map((d) => <th key={d.value}>{d.label}</th>)}<th>Tổng</th></tr></thead><tbody>{chapters.map((chapter) => { const rowTotal = DIFFICULTIES.reduce((sum, d) => sum + Number(quantities[keyOf(chapter.id, d.value)] || 0), 0); return <tr key={chapter.id}><td><strong>{chapter.orderIndex}. {chapter.name}</strong></td>{DIFFICULTIES.map((d) => { const key = keyOf(chapter.id, d.value); const available = availability.find((x) => x.chapterId === chapter.id && x.difficulty === d.value)?.available || 0; const value = Number(quantities[key] || 0); return <td key={d.value}><input aria-label={`${chapter.name} - ${d.label}`} className={value > available ? 'invalid-input' : ''} type="number" min="0" step="1" value={value} onChange={(e) => setQuantity(key, Math.max(0, Math.floor(Number(e.target.value) || 0)))} /><small className={value > available ? 'danger-text' : ''}>Có {available}{value > available ? ` · thiếu ${value - available}` : ''}</small></td> })}<td><strong>{rowTotal}</strong></td></tr> })}</tbody></table></div>
}

function MatrixForm({ item, subjects, allChapters, onClose }) {
  const queryClient = useQueryClient(); const { notify } = useToast(); const initialSubject = item?.subjectId || ''; const [subjectId, setSubjectId] = useState(initialSubject); const [quantities, setQuantities] = useState(() => Object.fromEntries((item?.configs || []).map((c) => [keyOf(c.chapterId, c.difficulty), c.quantity]))); const [configError, setConfigError] = useState('')
  const { register, handleSubmit, setError, formState: { errors } } = useForm({ defaultValues: item || { title: '', duration: 45, totalQuestions: 20 } }); const availability = useQuery({ queryKey: ['availability', subjectId], queryFn: () => api.getAvailability({ subjectId }), enabled: Boolean(subjectId) }); const chapters = useMemo(() => allChapters.filter((c) => c.subjectId === Number(subjectId)), [allChapters, subjectId])
  const mutation = useMutation({ mutationFn: (body) => item ? api.updateMatrix(item.id, body) : api.createMatrix(body), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['matrices'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); notify(item ? 'Đã cập nhật ma trận' : 'Đã thêm ma trận'); onClose() }, onError: (error) => setError('root', { message: error.message }) })
  const totalConfigured = Object.values(quantities).reduce((sum, value) => sum + Number(value || 0), 0)
  const submit = (values) => {
    setConfigError(''); if (!subjectId) return setError('subjectId', { message: 'Vui lòng chọn môn học' })
    const total = Number(values.totalQuestions); if (totalConfigured !== total) return setConfigError(`Tổng cấu hình hiện là ${totalConfigured}, phải bằng ${total} câu.`)
    const over = (availability.data || []).find((a) => Number(quantities[keyOf(a.chapterId, a.difficulty)] || 0) > a.available); if (over) return setConfigError('Cấu hình đang yêu cầu nhiều hơn số câu hỏi khả dụng.')
    const configs = Object.entries(quantities).filter(([, quantity]) => Number(quantity) > 0).map(([key, quantity]) => { const [chapterId, difficulty] = key.split('-'); return { chapterId: Number(chapterId), difficulty, quantity: Number(quantity) } })
    mutation.mutate({ subjectId: Number(subjectId), title: values.title.trim(), duration: Number(values.duration), totalQuestions: total, configs })
  }
  return <Modal title={item ? 'Sửa ma trận đề' : 'Thêm ma trận đề'} onClose={onClose} wide><form onSubmit={handleSubmit(submit)}>{errors.root && <div className="alert error">{errors.root.message}</div>}<div className="form-grid two"><label>Tiêu đề<input maxLength="100" {...register('title', { required: 'Tiêu đề là bắt buộc', maxLength: { value: 100, message: 'Tối đa 100 ký tự' } })} /></label><label>Môn học<select value={subjectId} onChange={(e) => { setSubjectId(e.target.value); setQuantities({}); setConfigError('') }} disabled={Boolean(item)}><option value="">Chọn môn học</option>{subjects.map((s) => <option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select></label><FieldError>{errors.title?.message}</FieldError><FieldError>{errors.subjectId?.message}</FieldError><label>Thời gian (phút)<input type="number" min="1" {...register('duration', { valueAsNumber: true, required: 'Thời gian là bắt buộc', min: { value: 1, message: 'Thời gian phải lớn hơn 0' } })} /></label><label>Tổng số câu<input type="number" min="1" {...register('totalQuestions', { valueAsNumber: true, required: 'Tổng số câu là bắt buộc', min: { value: 1, message: 'Tổng số câu phải lớn hơn 0' } })} /></label><FieldError>{errors.duration?.message}</FieldError><FieldError>{errors.totalQuestions?.message}</FieldError></div>
    <div className="section-heading"><div><h3>Cấu hình số lượng câu</h3><p>Nhập số câu cho từng chương và mức độ. Tổng hiện tại: <strong>{totalConfigured}</strong></p></div></div>{!subjectId ? <div className="state-box">Chọn môn học để cấu hình.</div> : availability.isLoading ? <LoadingState label="Đang kiểm tra số câu khả dụng..." /> : !chapters.length ? <EmptyState title="Môn học chưa có chương" /> : <ConfigTable chapters={chapters} availability={availability.data || []} quantities={quantities} setQuantity={(key, value) => setQuantities((prev) => ({ ...prev, [key]: value }))} />}<FieldError>{configError}</FieldError><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Hủy</button><button className="button" disabled={mutation.isPending || availability.isLoading}>{mutation.isPending ? 'Đang lưu...' : 'Lưu ma trận'}</button></div></form></Modal>
}

export default function MatricesPage() {
  const [filters, setFilters] = useState({ search: '', subjectId: '', page: 0, size: 10 }); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const queryClient = useQueryClient(); const { notify } = useToast(); const subjects = useQuery({ queryKey: ['subjects'], queryFn: api.getSubjects }); const chapters = useQuery({ queryKey: ['chapters', 'all'], queryFn: () => api.getChapters({}) }); const matrices = useQuery({ queryKey: ['matrices', filters], queryFn: () => api.getMatrices(filters) })
  const deleteMutation = useMutation({ mutationFn: api.deleteMatrix, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['matrices'] }); notify('Đã xóa ma trận'); setDeleting(null) }, onError: (error) => notify(error.message, 'error') }); const setFilter = (name, value) => setFilters((prev) => ({ ...prev, [name]: value, page: name === 'page' ? value : 0 }))
  return <><PageHeader title="Quản lý ma trận đề" description="Thiết lập cơ cấu câu hỏi theo chương và độ khó." action={<button className="button" onClick={() => setEditing({})}>Thêm ma trận</button>} /><div className="toolbar"><label className="search-field">Tìm kiếm<input value={filters.search} onChange={(e) => setFilter('search', e.target.value)} placeholder="Nhập tiêu đề ma trận" /></label><label>Môn học<select value={filters.subjectId} onChange={(e) => setFilter('subjectId', e.target.value)}><option value="">Tất cả môn học</option>{(subjects.data || []).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div>
    {matrices.isLoading ? <LoadingState /> : matrices.isError ? <ErrorState error={matrices.error} onRetry={matrices.refetch} /> : !matrices.data.content.length ? <EmptyState title="Chưa có ma trận đề" /> : <><div className="table-wrap"><table><thead><tr><th>Tiêu đề</th><th>Môn học</th><th>Thời gian</th><th>Số câu</th><th>Cập nhật</th><th>Thao tác</th></tr></thead><tbody>{matrices.data.content.map((item) => <tr key={item.id}><td><strong>{item.title}</strong></td><td>{(subjects.data || []).find((s) => s.id === item.subjectId)?.name || '—'}</td><td>{item.duration} phút</td><td>{item.totalQuestions}</td><td>{formatDate(item.updatedAt)}</td><td><div className="table-actions"><Link className="text-button" to={`/ma-tran/${item.id}`}>Xem chi tiết</Link><button className="text-button" onClick={() => setEditing(item)}>Sửa</button><button className="text-button danger-text" onClick={() => setDeleting(item)}>Xóa</button></div></td></tr>)}</tbody></table></div><Pagination page={matrices.data.page} totalPages={matrices.data.totalPages} onChange={(page) => setFilter('page', page)} /></>}
    {editing && <MatrixForm item={editing.id ? editing : null} subjects={subjects.data || []} allChapters={chapters.data || []} onClose={() => setEditing(null)} />}{deleting && <ConfirmModal message={`Xóa ma trận “${deleting.title}”?`} onClose={() => setDeleting(null)} onConfirm={() => deleteMutation.mutate(deleting.id)} busy={deleteMutation.isPending} />}
  </>
}

export function MatrixDetailPage() {
  const { id } = useParams(); const { notify } = useToast(); const queryClient = useQueryClient(); const [number, setNumber] = useState(1); const matrix = useQuery({ queryKey: ['matrix', id], queryFn: () => api.getMatrix(id) }); const subjects = useQuery({ queryKey: ['subjects'], queryFn: api.getSubjects }); const chapters = useQuery({ queryKey: ['chapters', 'all'], queryFn: () => api.getChapters({}) }); const availability = useQuery({ queryKey: ['availability', matrix.data?.subjectId], queryFn: () => api.getAvailability({ subjectId: matrix.data.subjectId }), enabled: Boolean(matrix.data) }); const papers = useQuery({ queryKey: ['papers', id], queryFn: () => api.getPapers({ matrixId: id, page: 0, size: 100 }) })
  const generate = useMutation({ mutationFn: () => api.generatePapers(id, { numberOfPapers: Number(number) }), onSuccess: (items) => { queryClient.invalidateQueries({ queryKey: ['papers'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); notify(`Đã sinh ${items.length} mã đề`) }, onError: (error) => notify(error.message, 'error') })
  if (matrix.isLoading || subjects.isLoading || chapters.isLoading) return <LoadingState />
  if (matrix.isError || !matrix.data) return <ErrorState error={matrix.error || new Error('Không tìm thấy ma trận')} onRetry={matrix.refetch} />
  const subject = subjects.data.find((s) => s.id === matrix.data.subjectId); const invalid = matrix.data.configs.some((c) => c.quantity > ((availability.data || []).find((a) => a.chapterId === c.chapterId && a.difficulty === c.difficulty)?.available || 0)); const total = matrix.data.configs.reduce((sum, c) => sum + c.quantity, 0); const canGenerate = !invalid && total === matrix.data.totalQuestions
  return <><PageHeader title={matrix.data.title} description={`${subject?.name || ''} · Cập nhật ${formatDate(matrix.data.updatedAt)}`} action={<Link className="button secondary" to="/ma-tran">Quay lại</Link>} /><section className="detail-summary"><div><span>Thời gian</span><strong>{matrix.data.duration} phút</strong></div><div><span>Tổng số câu</span><strong>{matrix.data.totalQuestions}</strong></div><div><span>Số cấu hình</span><strong>{matrix.data.configs.length}</strong></div><div><span>Đề đã sinh</span><strong>{papers.data?.totalElements || 0}</strong></div></section>
    <section className="panel"><div className="panel-heading"><h2>Cấu hình ma trận</h2>{canGenerate ? <Badge tone="success">Hợp lệ</Badge> : <Badge tone="danger">Chưa hợp lệ</Badge>}</div><div className="table-wrap"><table><thead><tr><th>Chương</th><th>Độ khó</th><th>Số lượng</th><th>Khả dụng</th><th>Trạng thái</th></tr></thead><tbody>{matrix.data.configs.map((config) => { const available = (availability.data || []).find((a) => a.chapterId === config.chapterId && a.difficulty === config.difficulty)?.available || 0; return <tr key={keyOf(config.chapterId, config.difficulty)}><td>{chapters.data.find((c) => c.id === config.chapterId)?.name}</td><td>{difficultyLabel(config.difficulty)}</td><td>{config.quantity}</td><td>{available}</td><td>{config.quantity <= available ? <Badge tone="success">Đủ câu hỏi</Badge> : <Badge tone="danger">Thiếu {config.quantity - available} câu</Badge>}</td></tr> })}</tbody></table></div>{total !== matrix.data.totalQuestions && <div className="alert error">Tổng cấu hình {total} không bằng tổng số câu {matrix.data.totalQuestions}.</div>}</section>
    <section className="panel generate-panel"><div><h2>Sinh đề thi</h2><p>Tạo các mã đề có thứ tự câu hỏi và đáp án được xáo trộn.</p></div><label>Số mã đề<input type="number" min="1" max="20" value={number} onChange={(e) => setNumber(Math.max(1, Math.min(20, Number(e.target.value) || 1)))} /></label><button className="button" disabled={!canGenerate || generate.isPending} onClick={() => generate.mutate()}>{generate.isPending ? 'Đang sinh đề...' : 'Sinh đề'}</button></section>
    <section className="panel"><div className="panel-heading"><h2>Danh sách đề đã sinh</h2><Link to={`/de-thi?matrixId=${id}`}>Xem tất cả</Link></div>{papers.isLoading ? <LoadingState /> : papers.data?.content.length ? <div className="compact-list">{papers.data.content.slice(0, 5).map((paper) => <Link to={`/de-thi/${paper.id}`} key={paper.id}><strong>Mã đề {paper.examCode}</strong><span>{paper.questions.length} câu · {formatDate(paper.createdAt)}</span></Link>)}</div> : <EmptyState title="Chưa sinh đề" description="Nhập số lượng mã đề và chọn Sinh đề." />}</section>
  </>
}
