import { useForm } from 'react-hook-form'
import { useMutation } from '@tanstack/react-query'
import { api } from '../api/service'
import { useAuth } from '../auth/AuthContext'
import { roleLabel } from '../constants'
import { FieldError, PageHeader } from '../components/UI'
import { useToast } from '../components/ToastProvider'

export default function ProfilePage() {
  const { user, updateLocalUser } = useAuth(); const { notify } = useToast()
  const profile = useForm({ defaultValues: { fullName: user.fullName, email: user.email } }); const password = useForm({ defaultValues: { currentPassword: '', newPassword: '', confirmPassword: '' } })
  const update = useMutation({ mutationFn: api.updateProfile, onSuccess: (next) => { updateLocalUser(next); notify('Đã cập nhật hồ sơ') }, onError: (error) => { Object.entries(error.fieldErrors || {}).forEach(([name, message]) => profile.setError(name, { message })); if (!error.fieldErrors || !Object.keys(error.fieldErrors).length) profile.setError('root', { message: error.message }) } })
  const change = useMutation({ mutationFn: api.changePassword, onSuccess: () => { password.reset(); notify('Đã đổi mật khẩu') }, onError: (error) => { Object.entries(error.fieldErrors || {}).forEach(([name, message]) => password.setError(name, { message })); if (!error.fieldErrors || !Object.keys(error.fieldErrors).length) password.setError('root', { message: error.message }) } })
  const changePassword = (values) => { if (values.newPassword !== values.confirmPassword) return password.setError('confirmPassword', { message: 'Mật khẩu xác nhận không khớp' }); const { confirmPassword: _confirmPassword, ...body } = values; change.mutate(body) }
  return <><PageHeader title="Hồ sơ cá nhân" description="Cập nhật thông tin liên hệ và mật khẩu đăng nhập." /><div className="profile-grid"><section className="panel"><h2>Thông tin tài khoản</h2><dl className="account-summary"><div><dt>Tên đăng nhập</dt><dd>{user.username}</dd></div><div><dt>Vai trò</dt><dd>{roleLabel(user.role)}</dd></div></dl><form onSubmit={profile.handleSubmit((values) => update.mutate(values))}>{profile.formState.errors.root && <div className="alert error">{profile.formState.errors.root.message}</div>}<label>Họ và tên<input maxLength="100" {...profile.register('fullName', { required: 'Họ tên là bắt buộc' })} /></label><FieldError>{profile.formState.errors.fullName?.message}</FieldError><label>Email<input type="email" {...profile.register('email', { required: 'Email là bắt buộc', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Email không hợp lệ' } })} /></label><FieldError>{profile.formState.errors.email?.message}</FieldError><button className="button" disabled={update.isPending}>{update.isPending ? 'Đang lưu...' : 'Cập nhật hồ sơ'}</button></form></section>
    <section className="panel"><h2>Đổi mật khẩu</h2><form onSubmit={password.handleSubmit(changePassword)}>{password.formState.errors.root && <div className="alert error">{password.formState.errors.root.message}</div>}<label>Mật khẩu hiện tại<input type="password" autoComplete="current-password" {...password.register('currentPassword', { required: 'Vui lòng nhập mật khẩu hiện tại' })} /></label><FieldError>{password.formState.errors.currentPassword?.message}</FieldError><label>Mật khẩu mới<input type="password" autoComplete="new-password" {...password.register('newPassword', { required: 'Vui lòng nhập mật khẩu mới', minLength: { value: 8, message: 'Mật khẩu cần ít nhất 8 ký tự' } })} /></label><FieldError>{password.formState.errors.newPassword?.message}</FieldError><label>Xác nhận mật khẩu mới<input type="password" autoComplete="new-password" {...password.register('confirmPassword', { required: 'Vui lòng xác nhận mật khẩu' })} /></label><FieldError>{password.formState.errors.confirmPassword?.message}</FieldError><button className="button" disabled={change.isPending}>{change.isPending ? 'Đang đổi...' : 'Đổi mật khẩu'}</button></form></section></div>
  </>
}
