import { useEffect, useMemo, useState } from 'react'
import { useFieldArray, useForm } from 'react-hook-form'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/service'
import { DIFFICULTIES, QUESTION_TYPES, difficultyLabel, typeLabel } from '../constants'
import { Badge, ConfirmModal, EmptyState, ErrorState, FieldError, LoadingState, Modal, PageHeader, Pagination } from '../components/UI'
import { useToast } from '../components/ToastProvider'

const blankAnswers = [{ content: '', isCorrect: true }, { content: '', isCorrect: false }]

function QuestionForm({ item, subjects, allChapters, onClose }) {
  const queryClient = useQueryClient(); const { notify } = useToast(); const [answerError, setAnswerError] = useState('')
  const { register, control, watch, handleSubmit, setError, setValue, formState: { errors } } = useForm({ defaultValues: item ? structuredClone(item) : { subjectId: '', chapterId: '', content: '', difficulty: 'MEDIUM', type: 'SINGLE_CHOICE', answers: blankAnswers } })
  const { fields, append, remove, replace } = useFieldArray({ control, name: 'answers' }); const type = watch('type'); const subjectId = watch('subjectId') || allChapters.find((c) => c.id === Number(watch('chapterId')))?.subjectId || ''; const answers = watch('answers')
  const chapters = useMemo(() => allChapters.filter((c) => c.subjectId === Number(subjectId)), [allChapters, subjectId])
  useEffect(() => { if (type === 'TRUE_FALSE') replace([{ content: 'Đúng', isCorrect: true }, { content: 'Sai', isCorrect: false }]) }, [type, replace])
  const mutation = useMutation({ mutationFn: (body) => item ? api.updateQuestion(item.id, body) : api.createQuestion(body), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['questions'] }); queryClient.invalidateQueries({ queryKey: ['availability'] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }); notify(item ? 'Đã cập nhật câu hỏi' : 'Đã thêm câu hỏi'); onClose() }, onError: (error) => setError('root', { message: error.message }) })
  const submit = (values) => {
    setAnswerError(''); const correct = values.answers.filter((a) => a.isCorrect).length
    if (values.answers.length < 2) return setAnswerError('Câu hỏi cần ít nhất hai đáp án')
    if (values.type !== 'MULTIPLE_CHOICE' && correct !== 1) return setAnswerError('Loại câu hỏi này phải có đúng một đáp án đúng')
    if (values.type === 'MULTIPLE_CHOICE' && correct < 1) return setAnswerError('Phải chọn ít nhất một đáp án đúng')
    const { subjectId: _subjectId, ...payload } = values; mutation.mutate({ ...payload, chapterId: Number(payload.chapterId) })
  }
  const toggleCorrect = (index) => { if (type !== 'MULTIPLE_CHOICE') answers.forEach((_, i) => setValue(`answers.${i}.isCorrect`, i === index)) }
  return <Modal title={item ? 'Sửa câu hỏi' : 'Thêm câu hỏi'} onClose={onClose} wide><form onSubmit={handleSubmit(submit)} noValidate>{errors.root && <div className="alert error">{errors.root.message}</div>}<div className="form-grid two"><label>Môn học<select value={subjectId} onChange={(e) => { setValue('subjectId', e.target.value); setValue('chapterId', '') }}><option value="">Chọn môn học</option>{subjects.map((s) => <option key={s.id} value={s.id}>{s.code} - {s.name}</option>)}</select></label><label>Chương<select {...register('chapterId', { required: 'Vui lòng chọn chương' })}><option value="">Chọn chương</option>{chapters.map((c) => <option key={c.id} value={c.id}>{c.orderIndex}. {c.name}</option>)}</select></label><span /><FieldError>{errors.chapterId?.message}</FieldError><label>Độ khó<select {...register('difficulty')}>{DIFFICULTIES.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Loại câu hỏi<select {...register('type')}>{QUESTION_TYPES.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label className="span-two">Nội dung câu hỏi<textarea rows="4" maxLength="3000" {...register('content', { required: 'Nội dung câu hỏi là bắt buộc' })} /></label><FieldError>{errors.content?.message}</FieldError></div>
    <fieldset className="answer-fieldset"><legend>Danh sách đáp án</legend>{fields.map((field, index) => <div className="answer-row" key={field.id}><label><input type={type === 'MULTIPLE_CHOICE' ? 'checkbox' : 'radio'} name="correct-answer" checked={Boolean(answers[index]?.isCorrect)} onChange={(e) => type === 'MULTIPLE_CHOICE' ? setValue(`answers.${index}.isCorrect`, e.target.checked) : toggleCorrect(index)} /> Đáp án đúng</label><div><input aria-label={`Nội dung đáp án ${index + 1}`} readOnly={type === 'TRUE_FALSE'} {...register(`answers.${index}.content`, { required: 'Không được để trống đáp án' })} /><FieldError>{errors.answers?.[index]?.content?.message}</FieldError></div>{type !== 'TRUE_FALSE' && fields.length > 2 && <button type="button" className="text-button danger-text" onClick={() => remove(index)}>Xóa dòng</button>}</div>)}{type !== 'TRUE_FALSE' && <button type="button" className="button secondary small" onClick={() => append({ content: '', isCorrect: false })}>Thêm dòng đáp án</button>}<FieldError>{answerError}</FieldError></fieldset>
    <div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Hủy</button><button className="button" disabled={mutation.isPending}>{mutation.isPending ? 'Đang lưu...' : 'Lưu câu hỏi'}</button></div></form></Modal>
}

function QuestionDetail({ item, chapter, subject, onClose }) {
  return <Modal title="Chi tiết câu hỏi" onClose={onClose} wide><div className="detail-meta"><span>Môn học<strong>{subject?.name}</strong></span><span>Chương<strong>{chapter?.name}</strong></span><span>Độ khó<strong>{difficultyLabel(item.difficulty)}</strong></span><span>Loại<strong>{typeLabel(item.type)}</strong></span></div><div className="question-content">{item.content}</div><ol className="answer-detail">{item.answers.map((a) => <li key={a.id || a.content} className={a.isCorrect ? 'correct-answer' : ''}>{a.content}{a.isCorrect && <Badge tone="success">Đáp án đúng</Badge>}</li>)}</ol></Modal>
}

export default function QuestionsPage() {
  const [filters, setFilters] = useState({ search: '', subjectId: '', chapterId: '', difficulty: '', type: '', page: 0, size: 8 }); const [editing, setEditing] = useState(null); const [viewing, setViewing] = useState(null); const [deleting, setDeleting] = useState(null); const { notify } = useToast(); const queryClient = useQueryClient()
  const subjects = useQuery({ queryKey: ['subjects'], queryFn: api.getSubjects }); const chapters = useQuery({ queryKey: ['chapters', 'all'], queryFn: () => api.getChapters({}) }); const questions = useQuery({ queryKey: ['questions', filters], queryFn: () => api.getQuestions(filters) })
  const deleteMutation = useMutation({ mutationFn: api.deleteQuestion, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['questions'] }); queryClient.invalidateQueries({ queryKey: ['availability'] }); notify('Đã xóa câu hỏi'); setDeleting(null) }, onError: (error) => notify(error.message, 'error') })
  const setFilter = (name, value) => setFilters((prev) => ({ ...prev, [name]: value, page: name === 'page' ? value : 0, ...(name === 'subjectId' ? { chapterId: '' } : {}) })); const filteredChapters = (chapters.data || []).filter((c) => !filters.subjectId || c.subjectId === Number(filters.subjectId))
  return <><PageHeader title="Ngân hàng câu hỏi" description="Tìm kiếm, phân loại và quản lý câu hỏi cùng đáp án." action={<button className="button" onClick={() => setEditing({})}>Thêm câu hỏi</button>} /><div className="toolbar multi"><label className="search-field">Tìm nội dung<input value={filters.search} onChange={(e) => setFilter('search', e.target.value)} placeholder="Nhập nội dung câu hỏi" /></label><label>Môn học<select value={filters.subjectId} onChange={(e) => setFilter('subjectId', e.target.value)}><option value="">Tất cả</option>{(subjects.data || []).map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Chương<select value={filters.chapterId} onChange={(e) => setFilter('chapterId', e.target.value)}><option value="">Tất cả</option>{filteredChapters.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Độ khó<select value={filters.difficulty} onChange={(e) => setFilter('difficulty', e.target.value)}><option value="">Tất cả</option>{DIFFICULTIES.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Loại<select value={filters.type} onChange={(e) => setFilter('type', e.target.value)}><option value="">Tất cả</option>{QUESTION_TYPES.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>
    {questions.isLoading ? <LoadingState /> : questions.isError ? <ErrorState error={questions.error} onRetry={questions.refetch} /> : !questions.data.content.length ? <EmptyState /> : <><div className="table-wrap"><table><thead><tr><th>Nội dung</th><th>Chương</th><th>Độ khó</th><th>Loại</th><th>Thao tác</th></tr></thead><tbody>{questions.data.content.map((item) => { const chapter = (chapters.data || []).find((c) => c.id === item.chapterId); return <tr key={item.id}><td className="question-cell">{item.content}</td><td>{chapter?.name || '—'}</td><td><Badge tone={item.difficulty === 'HARD' ? 'danger' : item.difficulty === 'MEDIUM' ? 'warning' : 'success'}>{difficultyLabel(item.difficulty)}</Badge></td><td>{typeLabel(item.type)}</td><td><div className="table-actions"><button className="text-button" onClick={() => setViewing(item)}>Xem</button><button className="text-button" onClick={() => setEditing(item)}>Sửa</button><button className="text-button danger-text" onClick={() => setDeleting(item)}>Xóa</button></div></td></tr> })}</tbody></table></div><Pagination page={questions.data.page} totalPages={questions.data.totalPages} onChange={(page) => setFilter('page', page)} /></>}
    {editing && <QuestionForm item={editing.id ? editing : null} subjects={subjects.data || []} allChapters={chapters.data || []} onClose={() => setEditing(null)} />}{viewing && (() => { const chapter = (chapters.data || []).find((c) => c.id === viewing.chapterId); return <QuestionDetail item={viewing} chapter={chapter} subject={(subjects.data || []).find((s) => s.id === chapter?.subjectId)} onClose={() => setViewing(null)} /> })()}{deleting && <ConfirmModal message="Xóa câu hỏi này khỏi ngân hàng?" onClose={() => setDeleting(null)} onConfirm={() => deleteMutation.mutate(deleting.id)} busy={deleteMutation.isPending} />}
  </>
}
