import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/service'
import { useAuth } from '../auth/AuthContext'
import { roleLabel } from '../constants'
import { formatDate } from '../utils'
import { Badge, EmptyState, ErrorState, FieldError, LoadingState, Modal, PageHeader, Pagination } from '../components/UI'
import { useToast } from '../components/ToastProvider'

function UserForm({ onClose }) {
  const { notify } = useToast(); const queryClient = useQueryClient(); const { register, handleSubmit, setError, formState: { errors } } = useForm({ defaultValues: { username: '', fullName: '', email: '', password: '' } })
  const mutation = useMutation({ mutationFn: api.createUser, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['users'] }); notify('Đã thêm tài khoản giáo viên'); onClose() }, onError: (error) => { Object.entries(error.fieldErrors || {}).forEach(([name, message]) => setError(name, { message })); if (!error.fieldErrors || !Object.keys(error.fieldErrors).length) setError('root', { message: error.message }) } })
  return <Modal title="Thêm tài khoản giáo viên" onClose={onClose}><form onSubmit={handleSubmit((values) => mutation.mutate(values))} noValidate>{errors.root && <div className="alert error">{errors.root.message}</div>}<label>Tên đăng nhập<input autoComplete="off" maxLength="50" {...register('username', { required: 'Tên đăng nhập là bắt buộc', pattern: { value: /^[a-zA-Z0-9._-]+$/, message: 'Chỉ dùng chữ, số, dấu chấm, gạch ngang' } })} /></label><FieldError>{errors.username?.message}</FieldError><label>Họ và tên<input maxLength="100" {...register('fullName', { required: 'Họ tên là bắt buộc' })} /></label><FieldError>{errors.fullName?.message}</FieldError><label>Email<input type="email" {...register('email', { required: 'Email là bắt buộc', pattern: { value: /^\S+@\S+\.\S+$/, message: 'Email không hợp lệ' } })} /></label><FieldError>{errors.email?.message}</FieldError><label>Mật khẩu ban đầu<input type="password" autoComplete="new-password" {...register('password', { required: 'Mật khẩu là bắt buộc', minLength: { value: 8, message: 'Mật khẩu cần ít nhất 8 ký tự' } })} /></label><FieldError>{errors.password?.message}</FieldError><div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Hủy</button><button className="button" disabled={mutation.isPending}>{mutation.isPending ? 'Đang lưu...' : 'Tạo tài khoản'}</button></div></form></Modal>
}

export default function UsersPage() {
  const { user } = useAuth(); const { notify } = useToast(); const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [filters, setFilters] = useState({ search: '', role: '', status: '', page: 0, size: 10 }); const users = useQuery({ queryKey: ['users', filters], queryFn: () => api.getUsers(filters) })
  const statusMutation = useMutation({ mutationFn: ({ id, status }) => api.updateUserStatus(id, status), onSuccess: (_, variables) => { queryClient.invalidateQueries({ queryKey: ['users'] }); notify(variables.status === 'LOCKED' ? 'Đã khóa tài khoản' : 'Đã mở khóa tài khoản') }, onError: (error) => notify(error.message, 'error') }); const setFilter = (name, value) => setFilters((prev) => ({ ...prev, [name]: value, page: name === 'page' ? value : 0 }))
  return <><PageHeader title="Quản lý người dùng" description="Quản lý tài khoản giáo viên và trạng thái truy cập." action={<button className="button" onClick={() => setOpen(true)}>Thêm giáo viên</button>} /><div className="toolbar multi"><label className="search-field">Tìm kiếm<input value={filters.search} onChange={(e) => setFilter('search', e.target.value)} placeholder="Tên, tài khoản hoặc email" /></label><label>Vai trò<select value={filters.role} onChange={(e) => setFilter('role', e.target.value)}><option value="">Tất cả</option><option value="ADMIN">Quản trị viên</option><option value="TEACHER">Giáo viên</option></select></label><label>Trạng thái<select value={filters.status} onChange={(e) => setFilter('status', e.target.value)}><option value="">Tất cả</option><option value="ACTIVE">Đang hoạt động</option><option value="LOCKED">Đã khóa</option></select></label></div>
    {users.isLoading ? <LoadingState /> : users.isError ? <ErrorState error={users.error} onRetry={users.refetch} /> : !users.data.content.length ? <EmptyState /> : <><div className="table-wrap"><table><thead><tr><th>Người dùng</th><th>Tên đăng nhập</th><th>Vai trò</th><th>Trạng thái</th><th>Ngày tạo</th><th>Thao tác</th></tr></thead><tbody>{users.data.content.map((item) => <tr key={item.id}><td><strong>{item.fullName}</strong><span className="subtext">{item.email}</span></td><td>{item.username}</td><td>{roleLabel(item.role)}</td><td><Badge tone={item.status === 'ACTIVE' ? 'success' : 'danger'}>{item.status === 'ACTIVE' ? 'Đang hoạt động' : 'Đã khóa'}</Badge></td><td>{formatDate(item.createdAt)}</td><td>{item.id === user.id ? <span className="muted">Tài khoản hiện tại</span> : <button className={`text-button ${item.status === 'ACTIVE' ? 'danger-text' : ''}`} disabled={statusMutation.isPending} onClick={() => statusMutation.mutate({ id: item.id, status: item.status === 'ACTIVE' ? 'LOCKED' : 'ACTIVE' })}>{item.status === 'ACTIVE' ? 'Khóa tài khoản' : 'Mở khóa'}</button>}</td></tr>)}</tbody></table></div><Pagination page={users.data.page} totalPages={users.data.totalPages} onChange={(page) => setFilter('page', page)} /></>}{open && <UserForm onClose={() => setOpen(false)} />}
  </>
}
